# Generated by Django 3.0.3 on 2023-02-24 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemcategory', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='PasItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password_id', models.CharField(max_length=256)),
                ('username', models.CharField(max_length=256)),
                ('password', models.CharField(max_length=256)),
                ('url', models.CharField(blank=True, max_length=256)),
                ('comment', models.CharField(blank=True, max_length=256)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='passkeeper.Category')),
            ],
        ),
    ]
