# Generated by Django 3.0.3 on 2023-02-24 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('passkeeper', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pasitem',
            old_name='category',
            new_name='pass_category',
        ),
    ]
