# Generated by Django 3.0.3 on 2023-03-09 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passkeeper', '0004_appuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='salt',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
