# Generated by Django 3.0.3 on 2023-03-10 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('passkeeper', '0006_auto_20230310_1010'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appuser',
            name='created_at',
        ),
    ]
