# Generated by Django 3.0.3 on 2023-03-10 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passkeeper', '0008_pasitemtemplate'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemcategory_temp', models.CharField(max_length=256)),
            ],
        ),
    ]
